# Generated by Django 5.0.3 on 2025-07-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0002_purchase_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
