# Generated by Django 5.0.3 on 2025-07-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cave", "0003_alter_category_options_category_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "regions",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="reference",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="references",
                to="cave.region",
            ),
        ),
    ]
