# Generated by Django 5.0.3 on 2025-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cave", "0004_region_reference_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
