# Generated by Django 5.0.3 on 2026-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0008_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reference',
            name='retail_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
