# Generated by Django 5.0.3 on 2026-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0009_add_retail_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='hidden_from_menu',
            field=models.BooleanField(default=False),
        ),
    ]
