# Generated by Django 6.0.2 on 2026-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0011_add_menu_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appellation',
            options={'ordering': ['name'], 'verbose_name_plural': 'appellations'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name_plural': 'regions'},
        ),
        migrations.RemoveField(
            model_name='appellation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='region',
            name='order',
        ),
    ]
