# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0012_alter_appellation_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
