# Generated by Django 5.0.3 on 2026-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0015_format_reference_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
