"""
Django settings for gibolin project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-lduej(vrbvcf&vjb2w3fk^3_tkz=l-lt4e!p2+@b&ut)7mipl6"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "localhost,api").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "cave",
    "users.apps.UsersConfig",
    "corsheaders",
    "mozilla_django_oidc",
    "django_use_email_as_username.apps.DjangoUseEmailAsUsernameConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
]

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000"
).split(",")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# OIDC Configuration (Google)
OIDC_RP_CLIENT_ID = os.getenv("OIDC_RP_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_RP_CLIENT_SECRET", "")
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
OIDC_OP_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
OIDC_OP_USER_ENDPOINT = "https://openidconnect.googleapis.com/v1/userinfo"
OIDC_OP_JWKS_ENDPOINT = "https://www.googleapis.com/oauth2/v3/certs"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_ENABLED = bool(OIDC_RP_CLIENT_ID)

AUTHENTICATION_BACKENDS = [
    "cave.auth.GibolinOIDCBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Add SessionRefresh when OIDC is configured, or DevAutoLogin in dev
if OIDC_ENABLED:
    MIDDLEWARE.append("mozilla_django_oidc.middleware.SessionRefresh")
elif DEBUG:
    MIDDLEWARE.append("cave.middleware.DevAutoLoginMiddleware")

ROOT_URLCONF = "gibolin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gibolin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRESQL_ADDON_DB", os.getenv("POSTGRES_DB", "gibolin")),
        "USER": os.getenv("POSTGRESQL_ADDON_USER", os.getenv("POSTGRES_USER", "gibolin")),
        "PASSWORD": os.getenv("POSTGRESQL_ADDON_PASSWORD", os.getenv("POSTGRES_PASSWORD", "gibolin")),
        "HOST": os.getenv("POSTGRESQL_ADDON_HOST", os.getenv("POSTGRES_HOST", "postgres")),
        "PORT": os.getenv("POSTGRESQL_ADDON_PORT", os.getenv("POSTGRES_PORT", "5432")),
    }
}

# Custom user model
AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Vite builds frontend assets with root-relative paths (/assets/...).
# WHITENOISE_ROOT serves them at the root URL path, matching what the HTML expects.
WHITENOISE_ROOT = str(BASE_DIR / ".." / "ui" / "dist")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Session security
SESSION_COOKIE_HTTPONLY = True
_scs = os.getenv("SESSION_COOKIE_SECURE")
SESSION_COOKIE_SECURE = _scs.lower() in ("true", "1", "yes") if _scs is not None else not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 86400 * 7  # 1 week

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
